import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Nav from "./appComponents/nav/Nav";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
